---
- name: Create ACL in Cisco ISE
  hosts: ise
  connection: local

  vars:
    ise_host: "150.1.7.111"
    ise_base_url: "https://{{ ise_host }}/ers/config"
    ise_username: "admin"
    ise_password: "Cisco123"
    acl_name: "AnsibleACL"
    acl_description: "This is my ACL created throw ansible tower"
    acl_rules:
      - {
          "name": "Rule 1",
          "description": "This is rule 1",
          "actions": [
            {
              "service": {
                "id": "00000000-1111-2222-3333-444444444444"
              }
            }
          ],
          "conditions": [
            {
              "protocol": "tcp",
              "source": {
                "ipAddress": "{{ source_ip }}",
                "mask": "255.255.255.255"
              },
              "destination": {
                "ipAddress": "{{ dest_ip }}",
                "mask": "255.255.255.255"
              },
              "destinationPort": "80"
            }
          ]
        }

  tasks:
    - name: Create ACL
      uri:
        url: "{{ ise_base_url }}/access/ipv4acl"
        method: POST
        user: "{{ ise_username }}"
        password: "{{ ise_password }}"
        headers:
          Content-Type: "application/json"
        body: |
          {
            "IPV4ACL": {
              "name": "{{ acl_name }}",
              "description": "{{ acl_description }}",
              "aclcontent": "{{ acl_rules | to_json }}"
            }
          }
        validate_certs: no
        status_code: 201
        return_content: yes
      register: result
      
    - name: Print result
      debug:
        var: result