---
- name: Create network device in Cisco ISE
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  vars:
    ise_base_url: https://admin:Cisc0123_@150.1.7.111:9060/ers/config
    #network_device_name: my-switch
    #network_device_ip: 150.1.7.7
    #network_device_type: CiscoSwitch
    #network_device_shared_secret: Cisco123
  tasks:
    - name: Create network device
      ansible.builtin.uri:
       url: "{{ ise_base_url }}/networkdevice"
       method: POST
       validate_certs: no
       headers:
          Content-Type: "application/json"
          Accept: "application/json"
       body_format: json
       body:
           {
        "NetworkDevice": {
          "name": "test_device",
          "description": "testing device",
          "modelName": "3650",
          "authenticationSettings": {
            "networkProtocol": "RADIUS",
            "radiusSharedSecret": "Cisco123",
            "enableKeyWrap": false,
            "keyEncryptionKey": "",
            "keyInputFormat": "ASCII"
          },
          "profileName": "Cisco",
          "coaPort": 1700,
          "NetworkDeviceIPList": [
            {
              "ipaddress": "192.168.0.0",
              "mask": 16
                 }
                 ],
          "NetworkDeviceGroupList": [
                "Location#All Locations",
                "IPSEC#Is IPSEC Device#No",
                "Device Type#All Device Types"
              ]
               }
            }
       status_code: 201
      register: create_device_result
    - name: Print create device result
      debug:
        var: create_device_result.json
