- name: Configure Authentication and Authorization for Switch
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no

  vars:
    radius_server: 150.1.7.111
    radius_key: Cisc0123_
    interface: eth2  # Replace with the actual interface name
    fail_vlan: 1  # Replace with the appropriate VLAN number
    guest_vlan: 305  # Replace with the appropriate VLAN number
    auth_session: dot1x

  tasks:
    - name: Set wired_802.1X condition
      ios_command:
        commands:
          - radius server ISE
          - address ipv4 {{ radius_server }}
          - key {{ radius_key }}
          - aaa new-model
          - aaa authentication dot1x default group radius
          - dot1x system-auth-control
          - dot1x pae authenticator
          - interface {{ interface }}
          - dot1x port-control auto
          - dot1x host-mode multi-auth
          - dot1x auth-fail vlan {{ fail_vlan }}
          - dot1x guest-vlan {{ guest_vlan }}
          - dot1x reauthentication
          - dot1x timeout reauth-period 60
          - dot1x max-req 3
          - dot1x max-reauth-req 3
          - dot1x supplicant force-multicast
          - dot1x auth-session {{ auth_session }}
          - dot1x guest-vlan {{ guest_vlan }}
          - no shut
        prompt: '#'
      register: config_result
      when: "'wired_802.1X' in info.conditions"

    - name: Create Auth_SW4_Dot1x authentication profile
      ios_command:
        commands:
          - radius server ISE
          - address ipv4 {{ radius_server }}
          - key {{ radius_key }}
          - aaa new-model
          - aaa authentication dot1x default group radius
          - dot1x system-auth-control
          - dot1x pae authenticator
          - interface {{ interface }}
          - dot1x port-control auto
          - dot1x host-mode multi-auth
          - dot1x auth-fail vlan {{ fail_vlan }}
          - dot1x guest-vlan {{ guest_vlan }}
          - dot1x reauthentication
          - dot1x timeout reauth-period 60
          - dot1x max-req 3
          - dot1x max-reauth-req 3
          - dot1x supplicant force-multicast
          - dot1x auth-session {{ auth_session }}
          - dot1x guest-vlan {{ guest_vlan }}
          - no shut
        prompt: '#'
      register: config_result
      

    - name: Configure Authorization for Switch
      ios_command:
        commands:
          - aaa authorization exec default group PFE_AD:ExternalGroups if-authenticated
          - aaa authorization commands 1 default group PFE_AD:ExternalGroups if-authenticated
          - aaa authorization commands 15 default group PFE_AD:ExternalGroups if-authenticated
        prompt: '#'
      register: config_result
      when: "'PFE_AD:ExternalGroups' in info.authorization"

    - name: Configure Authorization profile
      ios_command:
        commands:
          - aaa authorization exec default group
