---
 -name: Create Policy Set in Cisco ISE
  hosts: ISE2
  connection: local
  gather_facts: no

  vars:
    ise_server: "https://150.1.7.111:9060"
    ise_username: "admin"
    ise_password: "Cisc0123"
    policy_set_name: "PolicyAnsible"
    policy_set_desc: "This is a sample policy set."
    policy_set_condition: "Endpoint:PEE_AD·ExternalGroups:pfe.lab/Sales_group"

  tasks:
  - name: Get Authorization Profiles
    uri:
      url: "{{ ise_server }}/ers/config/authorizationprofile"
      method: GET
      user: "{{ ise_username }}"
      password: "{{ ise_password }}"
      validate_certs: False
    register: authorization_profiles

  - name: Create Policy Set
    uri:
      url: "{{ ise_server }}/ers/config/policyset"
      method: POST
      user: "{{ ise_username }}"
      password: "{{ ise_password }}"
      body_format: json
      body:
        name: "{{ policy_set_name }}"
        description: "{{ policy_set_desc }}"
        policyType: 1
        conditions:
          - type: 0
            attributeId: 1.3.6.1.4.1.9.9.468.1.2.2
            value: "{{ policy_set_condition }}"
        hitCounts: false
        enabled: true
        link:
          rel: "Link to Authorization Profiles"
          href: "{{ authorization_profiles.json.results[0].links.self.href }}"
          type: "application/json"
        conditionNegate: false
      headers:
        Accept: "application/json"
        Content-Type: "application/json"
      validate_certs: False
    register: policy_set_created

  - name: Print Response
    debug:
      var: policy_set_created.json