- name: POST Authorized Profile
  hosts: webservers
  connection: httpapi
  become: false
  gather_facts: no
  tasks:
    - name: Create Authorized Profile
      ansible.builtin.uri:
        url: "https://admin:Cisc0123_@150.1.7.111:9060/ers/config/authorizationprofile"
        method: POST
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
          ERS-Media-Type : policy.authorizationprofile.1.2
        body_format: json
        body:
         {
            "AuthorizationProfile": {
              "id": "",
              "name": "Ansible_Auth",
             "advancedAttributes": [
                      {
              "leftHandSideDictionaryAttribue": {
              "AdvancedAttributeValueType": "AdvancedDictionaryAttribute",
              "dictionaryName": "Cisco",
              "attributeName": "cisco-call-filter"
                                },
              "rightHandSideAttribueValue": {
               "AdvancedAttributeValueType": "AttributeValue",
               "value": "23"
                       }
                }
                ],
            "accessType": "ACCESS_ACCEPT",
            "authzProfileType": "SWITCH",
            "reauth": {
            "timer": 1800,
            "connectivity": "RADIUS_REQUEST"
                 }
                }
          }
        status_code: 201
      register: created_Authprofile

    - name: Display created Authorized profile
      debug:
        var: created_Authprofile.json
